const logos = {
  data: [
    {
      id: 1,
      name: "Apple",
      domain: "apple.com",
      category: "Technology",
      difficulty: "Easy",
    },
    {
      id: 2,
      name: "Google",
      domain: "google.com",
      category: "Technology",
      difficulty: "Easy",
    },
    {
      id: 3,
      name: "Microsoft",
      domain: "microsoft.com",
      category: "Technology",
      difficulty: "Easy",
    },
    {
      id: 4,
      name: "Amazon",
      domain: "amazon.com",
      category: "E-commerce",
      difficulty: "Easy",
    },
    {
      id: 5,
      name: "Meta",
      domain: "meta.com",
      category: "Technology",
      difficulty: "Easy",
    },
    {
      id: 6,
      name: "Netflix",
      domain: "netflix.com",
      category: "Streaming",
      difficulty: "Easy",
    },
    {
      id: 7,
      name: "Spotify",
      domain: "spotify.com",
      category: "Music",
      difficulty: "Easy",
    },
    {
      id: 8,
      name: "Adobe",
      domain: "adobe.com",
      category: "Software",
      difficulty: "Easy",
    },
    // {
    //   id: 9,
    //   name: "Intel",
    //   domain: "intel.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 10,
    //   name: "AMD",
    //   domain: "amd.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 11,
    //   name: "NVIDIA",
    //   domain: "nvidia.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 12,
    //   name: "Samsung",
    //   domain: "samsung.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 13,
    //   name: "LG",
    //   domain: "lg.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 14,
    //   name: "Sony",
    //   domain: "sony.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    {
      id: 15,
      name: "PlayStation",
      domain: "playstation.com",
      category: "Gaming",
      difficulty: "Easy",
    },
    {
      id: 16,
      name: "Xbox",
      domain: "xbox.com",
      category: "Gaming",
      difficulty: "Easy",
    },
    // {
    //   id: 17,
    //   name: "Nintendo",
    //   domain: "nintendo.com",
    //   category: "Gaming",
    //   difficulty: "Easy",
    // },
    {
      id: 18,
      name: "Steam",
      domain: "steampowered.com",
      category: "Gaming",
      difficulty: "Easy",
    },
    // {
    //   id: 19,
    //   name: "Epic Games",
    //   domain: "epicgames.com",
    //   category: "Gaming",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 20,
    //   name: "EA",
    //   domain: "ea.com",
    //   category: "Gaming",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 21,
    //   name: "Ubisoft",
    //   domain: "ubisoft.com",
    //   category: "Gaming",
    //   difficulty: "Easy",
    // },
    {
      id: 22,
      name: "Rockstar Games",
      domain: "rockstargames.com",
      category: "Gaming",
      difficulty: "Easy",
    },
    {
      id: 23,
      name: "Riot Games",
      domain: "riotgames.com",
      category: "Gaming",
      difficulty: "Easy",
    },
    // {
    //   id: 24,
    //   name: "Valve",
    //   domain: "valvesoftware.com",
    //   category: "Gaming",
    //   difficulty: "Medium",
    // },
    {
      id: 25,
      name: "Discord",
      domain: "discord.com",
      category: "Communication",
      difficulty: "Easy",
    },
    {
      id: 26,
      name: "Slack",
      domain: "slack.com",
      category: "Communication",
      difficulty: "Easy",
    },
    {
      id: 27,
      name: "Zoom",
      domain: "zoom.us",
      category: "Communication",
      difficulty: "Easy",
    },
    // {
    //   id: 28,
    //   name: "Skype",
    //   domain: "skype.com",
    //   category: "Communication",
    //   difficulty: "Medium",
    // },
    {
      id: 29,
      name: "LinkedIn",
      domain: "linkedin.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 30,
      name: "X",
      domain: "x.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 31,
      name: "Facebook",
      domain: "facebook.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 32,
      name: "Instagram",
      domain: "instagram.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 33,
      name: "WhatsApp",
      domain: "whatsapp.com",
      category: "Communication",
      difficulty: "Easy",
    },
    {
      id: 34,
      name: "Snapchat",
      domain: "snapchat.com",
      category: "Social Media",
      difficulty: "Medium",
    },
    {
      id: 35,
      name: "TikTok",
      domain: "tiktok.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 36,
      name: "Reddit",
      domain: "reddit.com",
      category: "Social Media",
      difficulty: "Easy",
    },
    {
      id: 37,
      name: "Pinterest",
      domain: "pinterest.com",
      category: "Social Media",
      difficulty: "Medium",
    },
    {
      id: 38,
      name: "Twitch",
      domain: "twitch.tv",
      category: "Streaming",
      difficulty: "Medium",
    },
    {
      id: 39,
      name: "YouTube",
      domain: "youtube.com",
      category: "Streaming",
      difficulty: "Easy",
    },
    {
      id: 40,
      name: "Vimeo",
      domain: "vimeo.com",
      category: "Streaming",
      difficulty: "Hard",
    },
    {
      id: 41,
      name: "Dropbox",
      domain: "dropbox.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 42,
      name: "GitHub",
      domain: "github.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 43,
      name: "GitLab",
      domain: "gitlab.com",
      category: "Software",
      difficulty: "Hard",
    },
    {
      id: 44,
      name: "Bitbucket",
      domain: "bitbucket.org",
      category: "Software",
      difficulty: "Hard",
    },
    {
      id: 45,
      name: "Atlassian",
      domain: "atlassian.com",
      category: "Software",
      difficulty: "Hard",
    },
    {
      id: 46,
      name: "Notion",
      domain: "notion.so",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 47,
      name: "Figma",
      domain: "figma.com",
      category: "Software",
      difficulty: "Medium",
    },
    // {
    //   id: 48,
    //   name: "Canva",
    //   domain: "canva.com",
    //   category: "Software",
    //   difficulty: "Easy",
    // },
    {
      id: 49,
      name: "Trello",
      domain: "trello.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 50,
      name: "Asana",
      domain: "asana.com",
      category: "Software",
      difficulty: "Hard",
    },
    // {
    //   id: 51,
    //   name: "Jira",
    //   domain: "atlassian.com",
    //   category: "Software",
    //   difficulty: "Medium",
    // },
    {
      id: 52,
      name: "Oracle",
      domain: "oracle.com",
      category: "Technology",
      difficulty: "Medium",
    },
    // {
    //   id: 53,
    //   name: "Cisco",
    //   domain: "cisco.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 54,
    //   name: "Dell",
    //   domain: "dell.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 55,
    //   name: "HP",
    //   domain: "hp.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 56,
    //   name: "Lenovo",
    //   domain: "lenovo.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 57,
    //   name: "Acer",
    //   domain: "acer.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    {
      id: 58,
      name: "ASUS",
      domain: "asus.com",
      category: "Technology",
      difficulty: "Easy",
    },
    // {
    //   id: 59,
    //   name: "MSI",
    //   domain: "msi.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    {
      id: 60,
      name: "Razer",
      domain: "razer.com",
      category: "Gaming",
      difficulty: "Medium",
    },
    {
      id: 61,
      name: "Corsair",
      domain: "corsair.com",
      category: "Gaming",
      difficulty: "Medium",
    },
    {
      id: 62,
      name: "Logitech",
      domain: "logitech.com",
      category: "Technology",
      difficulty: "Easy",
    },
    {
      id: 63,
      name: "SteelSeries",
      domain: "steelseries.com",
      category: "Gaming",
      difficulty: "Hard",
    },
    {
      id: 64,
      name: "HyperX",
      domain: "hyperx.com",
      category: "Gaming",
      difficulty: "Medium",
    },
    // {
    //   id: 65,
    //   name: "Alienware",
    //   domain: "alienware.com",
    //   category: "Gaming",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 66,
    //   name: "BenQ",
    //   domain: "benq.com",
    //   category: "Technology",
    //   difficulty: "Hard",
    // },
    // {
    //   id: 67,
    //   name: "Philips",
    //   domain: "philips.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 68,
    //   name: "Panasonic",
    //   domain: "panasonic.com",
    //   category: "Technology",
    //   difficulty: "Hard",
    // },
    // {
    //   id: 69,
    //   name: "Xiaomi",
    //   domain: "mi.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    {
      id: 70,
      name: "OnePlus",
      domain: "oneplus.com",
      category: "Technology",
      difficulty: "Medium",
    },
    // {
    //   id: 71,
    //   name: "Huawei",
    //   domain: "huawei.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 72,
    //   name: "Oppo",
    //   domain: "oppo.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 73,
    //   name: "Vivo",
    //   domain: "vivo.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 74,
    //   name: "Realme",
    //   domain: "realme.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    {
      id: 75,
      name: "Motorola",
      domain: "motorola.com",
      category: "Technology",
      difficulty: "Medium",
    },
    // {
    //   id: 76,
    //   name: "Nokia",
    //   domain: "nokia.com",
    //   category: "Technology",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 77,
    //   name: "Nothing",
    //   domain: "nothing.tech",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    {
      id: 78,
      name: "Tesla",
      domain: "tesla.com",
      category: "Automotive",
      difficulty: "Easy",
    },
    // {
    //   id: 79,
    //   name: "BMW",
    //   domain: "bmw.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    {
      id: 80,
      name: "Mercedes-Benz",
      domain: "mercedes-benz.com",
      category: "Automotive",
      difficulty: "Easy",
    },
    {
      id: 81,
      name: "Audi",
      domain: "audi.com",
      category: "Automotive",
      difficulty: "Easy",
    },
    {
      id: 82,
      name: "Volkswagen",
      domain: "vw.com",
      category: "Automotive",
      difficulty: "Easy",
    },
    {
      id: 83,
      name: "Toyota",
      domain: "toyota.com",
      category: "Automotive",
      difficulty: "Easy",
    },
    // {
    //   id: 84,
    //   name: "Honda",
    //   domain: "honda.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 85,
    //   name: "Hyundai",
    //   domain: "hyundai.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 86,
    //   name: "Kia",
    //   domain: "kia.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 87,
    //   name: "Ford",
    //   domain: "ford.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    {
      id: 88,
      name: "Chevrolet",
      domain: "chevrolet.com",
      category: "Automotive",
      difficulty: "Medium",
    },
    {
      id: 89,
      name: "Ferrari",
      domain: "ferrari.com",
      category: "Automotive",
      difficulty: "Medium",
    },
    {
      id: 90,
      name: "Lamborghini",
      domain: "lamborghini.com",
      category: "Automotive",
      difficulty: "Medium",
    },
    // {
    //   id: 91,
    //   name: "Porsche",
    //   domain: "porsche.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    {
      id: 92,
      name: "Bugatti",
      domain: "bugatti.com",
      category: "Automotive",
      difficulty: "Hard",
    },
    // {
    //   id: 93,
    //   name: "Volvo",
    //   domain: "volvocars.com",
    //   category: "Automotive",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 94,
    //   name: "Mazda",
    //   domain: "mazda.com",
    //   category: "Automotive",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 95,
    //   name: "Subaru",
    //   domain: "subaru.com",
    //   category: "Automotive",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 96,
    //   name: "Jeep",
    //   domain: "jeep.com",
    //   category: "Automotive",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 97,
    //   name: "Land Rover",
    //   domain: "landrover.com",
    //   category: "Automotive",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 98,
    //   name: "Jaguar",
    //   domain: "jaguar.com",
    //   category: "Automotive",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 99,
    //   name: "Ferrero",
    //   domain: "ferrero.com",
    //   category: "Food",
    //   difficulty: "Hard",
    // },
    {
      id: 100,
      name: "McDonald's",
      domain: "mcdonalds.com",
      category: "Food",
      difficulty: "Easy",
    },
    // {
    //   id: 101,
    //   name: "Burger King",
    //   domain: "burgerking.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    {
      id: 102,
      name: "KFC",
      domain: "kfc.com",
      category: "Food",
      difficulty: "Easy",
    },
    {
      id: 103,
      name: "Subway",
      domain: "subway.com",
      category: "Food",
      difficulty: "Easy",
    },
    {
      id: 104,
      name: "Domino's",
      domain: "dominos.com",
      category: "Food",
      difficulty: "Easy",
    },
    // {
    //   id: 105,
    //   name: "Pizza Hut",
    //   domain: "pizzahut.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    {
      id: 106,
      name: "Starbucks",
      domain: "starbucks.com",
      category: "Food",
      difficulty: "Easy",
    },
    // {
    //   id: 107,
    //   name: "Coca-Cola",
    //   domain: "coca-cola.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 108,
    //   name: "Pepsi",
    //   domain: "pepsi.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    {
      id: 109,
      name: "Nestlé",
      domain: "nestle.com",
      category: "Food",
      difficulty: "Medium",
    },
    // {
    //   id: 110,
    //   name: "KitKat",
    //   domain: "kitkat.com",
    //   category: "Food",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 111,
    //   name: "Pringles",
    //   domain: "pringles.com",
    //   category: "Food",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 112,
    //   name: "Oreo",
    //   domain: "oreo.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 113,
    //   name: "Lays",
    //   domain: "lays.com",
    //   category: "Food",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 114,
    //   name: "Doritos",
    //   domain: "doritos.com",
    //   category: "Food",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 115,
    //   name: "Prada",
    //   domain: "prada.com",
    //   category: "Fashion",
    //   difficulty: "Hard",
    // },
    // {
    //   id: 116,
    //   name: "Gucci",
    //   domain: "gucci.com",
    //   category: "Fashion",
    //   difficulty: "Easy",
    // },
    {
      id: 117,
      name: "Louis Vuitton",
      domain: "louisvuitton.com",
      category: "Fashion",
      difficulty: "Easy",
    },
    {
      id: 118,
      name: "Nike",
      domain: "nike.com",
      category: "Fashion",
      difficulty: "Easy",
    },
    {
      id: 119,
      name: "Adidas",
      domain: "adidas.com",
      category: "Fashion",
      difficulty: "Easy",
    },
    {
      id: 120,
      name: "Puma",
      domain: "puma.com",
      category: "Fashion",
      difficulty: "Easy",
    },
    {
      id: 121,
      name: "Reebok",
      domain: "reebok.com",
      category: "Fashion",
      difficulty: "Medium",
    },
    {
      id: 122,
      name: "New Balance",
      domain: "newbalance.com",
      category: "Fashion",
      difficulty: "Medium",
    },
    {
      id: 123,
      name: "Under Armour",
      domain: "underarmour.com",
      category: "Fashion",
      difficulty: "Medium",
    },
    // {
    //   id: 124,
    //   name: "Zara",
    //   domain: "zara.com",
    //   category: "Fashion",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 125,
    //   name: "H&M",
    //   domain: "hm.com",
    //   category: "Fashion",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 126,
    //   name: "Uniqlo",
    //   domain: "uniqlo.com",
    //   category: "Fashion",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 127,
    //   name: "Rolex",
    //   domain: "rolex.com",
    //   category: "Luxury",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 128,
    //   name: "Omega",
    //   domain: "omegawatches.com",
    //   category: "Luxury",
    //   difficulty: "Hard",
    // },
    // {
    //   id: 129,
    //   name: "Cartier",
    //   domain: "cartier.com",
    //   category: "Luxury",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 130,
    //   name: "Chanel",
    //   domain: "chanel.com",
    //   category: "Luxury",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 131,
    //   name: "Dior",
    //   domain: "dior.com",
    //   category: "Luxury",
    //   difficulty: "Easy",
    // },
    {
      id: 132,
      name: "Airbnb",
      domain: "airbnb.com",
      category: "Travel",
      difficulty: "Easy",
    },
    {
      id: 133,
      name: "Booking.com",
      domain: "booking.com",
      category: "Travel",
      difficulty: "Easy",
    },
    {
      id: 134,
      name: "Expedia",
      domain: "expedia.com",
      category: "Travel",
      difficulty: "Medium",
    },
    // {
    //   id: 135,
    //   name: "Uber",
    //   domain: "uber.com",
    //   category: "Travel",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 136,
    //   name: "Lyft",
    //   domain: "lyft.com",
    //   category: "Travel",
    //   difficulty: "Hard",
    // },
    {
      id: 137,
      name: "PayPal",
      domain: "paypal.com",
      category: "Finance",
      difficulty: "Easy",
    },
    // {
    //   id: 138,
    //   name: "Visa",
    //   domain: "visa.com",
    //   category: "Finance",
    //   difficulty: "Easy",
    // },
    {
      id: 139,
      name: "Mastercard",
      domain: "mastercard.com",
      category: "Finance",
      difficulty: "Easy",
    },
    {
      id: 140,
      name: "American Express",
      domain: "americanexpress.com",
      category: "Finance",
      difficulty: "Medium",
    },
    {
      id: 141,
      name: "Stripe",
      domain: "stripe.com",
      category: "Finance",
      difficulty: "Medium",
    },
    {
      id: 142,
      name: "Razorpay",
      domain: "razorpay.com",
      category: "Finance",
      difficulty: "Medium",
    },
    {
      id: 143,
      name: "PhonePe",
      domain: "phonepe.com",
      category: "Finance",
      difficulty: "Easy",
    },
    // {
    //   id: 144,
    //   name: "Google Pay",
    //   domain: "pay.google.com",
    //   category: "Finance",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 145,
    //   name: "Paytm",
    //   domain: "paytm.com",
    //   category: "Finance",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 146,
    //   name: "JBL",
    //   domain: "jbl.com",
    //   category: "Audio",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 147,
    //   name: "Bose",
    //   domain: "bose.com",
    //   category: "Audio",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 148,
    //   name: "Sennheiser",
    //   domain: "sennheiser.com",
    //   category: "Audio",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 149,
    //   name: "Marshall",
    //   domain: "marshall.com",
    //   category: "Audio",
    //   difficulty: "Medium",
    // },
    {
      id: 150,
      name: "Beats",
      domain: "beatsbydre.com",
      category: "Audio",
      difficulty: "Easy",
    },
    // {
    //   id: 151,
    //   name: "GoPro",
    //   domain: "gopro.com",
    //   category: "Cameras",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 152,
    //   name: "Canon",
    //   domain: "canon.com",
    //   category: "Cameras",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 153,
    //   name: "Nikon",
    //   domain: "nikon.com",
    //   category: "Cameras",
    //   difficulty: "Easy",
    // },
    // {
    //   id: 154,
    //   name: "Fujifilm",
    //   domain: "fujifilm.com",
    //   category: "Cameras",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 155,
    //   name: "Leica",
    //   domain: "leica-camera.com",
    //   category: "Cameras",
    //   difficulty: "Hard",
    // },
    {
      id: 156,
      name: "Shell",
      domain: "shell.com",
      category: "Energy",
      difficulty: "Medium",
    },
    {
      id: 157,
      name: "BP",
      domain: "bp.com",
      category: "Energy",
      difficulty: "Medium",
    },
    // {
    //   id: 158,
    //   name: "ExxonMobil",
    //   domain: "exxonmobil.com",
    //   category: "Energy",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 159,
    //   name: "IKEA",
    //   domain: "ikea.com",
    //   category: "Home",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 160,
    //   name: "Lego",
    //   domain: "lego.com",
    //   category: "Toys",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 161,
    //   name: "Mattel",
    //   domain: "mattel.com",
    //   category: "Toys",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 162,
    //   name: "Hasbro",
    //   domain: "hasbro.com",
    //   category: "Toys",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 163,
    //   name: "Intelbras",
    //   domain: "intelbras.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    {
      id: 164,
      name: "Cloudflare",
      domain: "cloudflare.com",
      category: "Technology",
      difficulty: "Medium",
    },
    {
      id: 165,
      name: "OpenAI",
      domain: "openai.com",
      category: "AI",
      difficulty: "Medium",
    },
    {
      id: 166,
      name: "Anthropic",
      domain: "anthropic.com",
      category: "AI",
      difficulty: "Medium",
    },
    {
      id: 167,
      name: "Perplexity",
      domain: "perplexity.ai",
      category: "AI",
      difficulty: "Medium",
    },
    {
      id: 168,
      name: "Databricks",
      domain: "databricks.com",
      category: "AI",
      difficulty: "Medium",
    },
    {
      id: 169,
      name: "Snowflake",
      domain: "snowflake.com",
      category: "Technology",
      difficulty: "Medium",
    },
    // {
    //   id: 170,
    //   name: "SAP",
    //   domain: "sap.com",
    //   category: "Software",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 171,
    //   name: "Salesforce",
    //   domain: "salesforce.com",
    //   category: "Software",
    //   difficulty: "Medium",
    // },
    {
      id: 172,
      name: "HubSpot",
      domain: "hubspot.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 173,
      name: "Mailchimp",
      domain: "mailchimp.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 174,
      name: "Duolingo",
      domain: "duolingo.com",
      category: "Education",
      difficulty: "Medium",
    },
    // {
    //   id: 175,
    //   name: "Coursera",
    //   domain: "coursera.org",
    //   category: "Education",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 176,
    //   name: "Udemy",
    //   domain: "udemy.com",
    //   category: "Education",
    //   difficulty: "Medium",
    // },
    {
      id: 177,
      name: "Khan Academy",
      domain: "khanacademy.org",
      category: "Education",
      difficulty: "Medium",
    },
    {
      id: 178,
      name: "CapCut",
      domain: "capcut.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 179,
      name: "InShot",
      domain: "inshot.com",
      category: "Software",
      difficulty: "Medium",
    },
    {
      id: 180,
      name: "Shazam",
      domain: "shazam.com",
      category: "Music",
      difficulty: "Medium",
    },
    {
      id: 181,
      name: "SoundCloud",
      domain: "soundcloud.com",
      category: "Music",
      difficulty: "Medium",
    },
    {
      id: 182,
      name: "Bandcamp",
      domain: "bandcamp.com",
      category: "Music",
      difficulty: "Medium",
    },
    {
      id: 183,
      name: "Mozilla",
      domain: "mozilla.org",
      category: "Technology",
      difficulty: "Medium",
    },
    {
      id: 184,
      name: "Opera",
      domain: "opera.com",
      category: "Technology",
      difficulty: "Medium",
    },
    {
      id: 185,
      name: "Brave",
      domain: "brave.com",
      category: "Technology",
      difficulty: "Medium",
    },
    // {
    //   id: 186,
    //   name: "Firefox",
    //   domain: "mozilla.org",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 187,
    //   name: "Chrome",
    //   domain: "google.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 188,
    //   name: "Safari",
    //   domain: "apple.com",
    //   category: "Technology",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 189,
    //   name: "Yamaha",
    //   domain: "yamaha.com",
    //   category: "Audio",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 190,
    //   name: "Casio",
    //   domain: "casio.com",
    //   category: "Electronics",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 191,
    //   name: "Brother",
    //   domain: "brother.com",
    //   category: "Electronics",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 192,
    //   name: "Epson",
    //   domain: "epson.com",
    //   category: "Electronics",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 193,
    //   name: "Seiko",
    //   domain: "seikowatches.com",
    //   category: "Luxury",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 194,
    //   name: "Tissot",
    //   domain: "tissotwatches.com",
    //   category: "Luxury",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 195,
    //   name: "Hilton",
    //   domain: "hilton.com",
    //   category: "Hospitality",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 196,
    //   name: "Marriott",
    //   domain: "marriott.com",
    //   category: "Hospitality",
    //   difficulty: "Medium",
    // },
    {
      id: 197,
      name: "Accor",
      domain: "all.com",
      category: "Hospitality",
      difficulty: "Medium",
    },
    // {
    //   id: 198,
    //   name: "Emirates",
    //   domain: "emirates.com",
    //   category: "Airlines",
    //   difficulty: "Medium",
    // },
    {
      id: 199,
      name: "Qatar Airways",
      domain: "qatarairways.com",
      category: "Airlines",
      difficulty: "Medium",
    },
    {
      id: 200,
      name: "Lufthansa",
      domain: "lufthansa.com",
      category: "Airlines",
      difficulty: "Medium",
    },
    // {
    //   id: 201,
    //   name: "Air India",
    //   domain: "airindia.com",
    //   category: "Airlines",
    //   difficulty: "Medium",
    // },
    {
      id: 202,
      name: "IndiGo",
      domain: "goindigo.in",
      category: "Airlines",
      difficulty: "Medium",
    },
    {
      id: 203,
      name: "Singapore Airlines",
      domain: "singaporeair.com",
      category: "Airlines",
      difficulty: "Medium",
    },
    // {
    //   id: 204,
    //   name: "FedEx",
    //   domain: "fedex.com",
    //   category: "Logistics",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 205,
    //   name: "UPS",
    //   domain: "ups.com",
    //   category: "Logistics",
    //   difficulty: "Medium",
    // },
    // {
    //   id: 206,
    //   name: "DHL",
    //   domain: "dhl.com",
    //   category: "Logistics",
    //   difficulty: "Medium",
    // },
    {
      id: 207,
      name: "ZeroSignal",
      domain: "",
      category: "Technology",
      difficulty: "Hard",
    },
  ],
};

export default logos;
